name: daily-idea-generator
on:
  schedule:
    - cron: '0 22 * * *'  # 07:00 JST
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      TWITTER_USER_ID: ${{ secrets.TWITTER_USER_ID }}      
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install openai httpx
     #  - run: python fetch_tweets.py
     #  - run: python aggregate_metrics.py
      - run: python call_openai.py
      - name: Commit ideas
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git add ideas.json
          git commit -m "feat: daily ideas $(date '+%Y-%m-%d')" || echo 'No changes'
          git push
